[package]
name = "lanlink-core"
version.workspace = true
edition.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
iroh.workspace = true
dirs.workspace = true
bytes = "1"
tracing-subscriber.workspace = true
tracing-appender = "0.2"
socket2 = { version = "0.6", features = ["all"] }
gethostname = "1"

[dev-dependencies]
iroh.workspace = true
